name: lumentrack-system
services:
  lumentrack-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: lumentrack-auth-api:0.2
    container_name: lumentrack-auth-backend-api
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      # Variables de entorno para la base de datos
      - AIVEN_DB_URL=${AIVEN_DB_URL}
      - AIVEN_DB_USER=${AIVEN_DB_USER}
      - AIVEN_DB_PASSWORD=${AIVEN_DB_PASSWORD}
      # Variables de entorno para JWT (AÑADIDAS)
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    # --- CONFIGURACIÓN DEL HEALTHCHECK ---
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"] # PUERTO CORREGIDO a 8084
      interval: 30s      # Tiempo entre pruebas
      timeout: 10s       # Tiempo de espera para la respuesta
      retries: 3         # Cuántos intentos fallidos antes de marcar como unhealthy
      start_period: 40s  # Tiempo que le damos a Spring para arrancar antes de empezar a probar
    restart: always