plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.lumentrack'
version = '0.0.1-SNAPSHOT'
description = 'admin-management'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    mavenLocal() // Añadido: Para encontrar lumentrack-commons
}

dependencies {
    // Dependencia a la librería común
    implementation 'com.lumentrack:lumentrack-commons:0.0.1-SNAPSHOT'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // Mantenido
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    // Eliminado: compileOnly 'org.projectlombok:lombok' (ahora en commons)
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    runtimeOnly 'com.mysql:mysql-connector-j' // Mantenido
    // Eliminado: annotationProcessor 'org.projectlombok:lombok' (ahora en commons)
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
    useJUnitPlatform()
}