// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu236wNx15SUG8qEsZSglZqhr_Fs0mf3g',
    appId: '1:100174188918:web:2de41daed78550270d6a57',
    messagingSenderId: '100174188918',
    projectId: 'lumentrack-zbksystems-dist',
    authDomain: 'lumentrack-zbksystems-dist.firebaseapp.com',
    storageBucket: 'lumentrack-zbksystems-dist.firebasestorage.app',
    measurementId: 'G-GTT8SZ8WDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlkjGIFDQZul0H13an1zNR9unbLXgm40U',
    appId: '1:100174188918:android:c5c869ce1c07412b0d6a57',
    messagingSenderId: '100174188918',
    projectId: 'lumentrack-zbksystems-dist',
    storageBucket: 'lumentrack-zbksystems-dist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEjsARsRnuUn3dusNhfUJouSlXnYQPfGs',
    appId: '1:100174188918:ios:a47d7cf7f91e5f580d6a57',
    messagingSenderId: '100174188918',
    projectId: 'lumentrack-zbksystems-dist',
    storageBucket: 'lumentrack-zbksystems-dist.firebasestorage.app',
    iosBundleId: 'com.example.lumentrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu236wNx15SUG8qEsZSglZqhr_Fs0mf3g',
    appId: '1:100174188918:web:5ca1c5aee91b2eb80d6a57',
    messagingSenderId: '100174188918',
    projectId: 'lumentrack-zbksystems-dist',
    authDomain: 'lumentrack-zbksystems-dist.firebaseapp.com',
    storageBucket: 'lumentrack-zbksystems-dist.firebasestorage.app',
    measurementId: 'G-XWDVK1N0DF',
  );
}
