plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.lumentrack'
version = '0.0.1-SNAPSHOT'

springBoot {
	buildInfo()
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	mavenLocal() // Añadido: Para encontrar lumentrack-commons
}

dependencies {
	// Dependencia a la librería común
	implementation 'com.lumentrack:lumentrack-commons:0.0.1-SNAPSHOT'

	implementation 'com.cloudinary:cloudinary-http5:2.0.0'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Re-añadidas: Dependencias necesarias para la aplicación principal
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'com.mysql:mysql-connector-j'

	// ELIMINADO: implementation 'org.springframework.boot:spring-boot-autoconfigure:4.0.5'
}

tasks.named('test') {
	useJUnitPlatform()
}